language: node_js
node_js:
- '12'
sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
    secure: akNi02RGIWC9rzJM4a/6yBF/HvyiYl7TGMNdkiWfcXJrx8tGMGMKGGBxgI/jO1VGcvsIcY1UmEq7OX2BYQabD9lqvTsh1dpykBXTuI5whyzfY1uKiRVeZuMTUuNrex/UCQ8NyWnZbWyNBAaiZRmVjOVBHslNR2I0hzjgxu20S9uyN5qzXRShpGFcej620uhfUHf/N5fr0LUFnsQtTMcVeHFbGnVGdOraaBKEV23hZd7xGESD9ddkL832CNkYtimm3MGRNAvkGQbVOZV9WlkC9DmkPmgJXf05h3SZfICioHwNPiDVpJpGvDQg7HwqmqLcu6GVbM7WAy/M422lYX+FebvBDjBXETFoMzLAK9i9ErG+PHad/TSupEOPZ24r2JjHP4NUx/JSj2jr8np6npSMnGlL79elffqr3h6xYLlOD9r16Y8J7RYHwfMUp+SHoTvgFZNfuqYCMoCc/Uqjcu+MlN/aqOtpnF/FvhsnL17bNMYLJcXyaB9syzuxN7q9qh8Xee1BMX9lJ0kU6CkP2YQQpCAgDcqrJ1gXzdaYzoVHCg45ACOzURC6hw6AtFGQB7+9wEQav/YM6E8P/WLNCf+JROSon8R+NaGz4AwrWFRgCxfiBgU18OWfojV2kCDLcSGQW2HL6FFfBNsfUkKnLEdP2zURHrjahLDFUAjDBPpytUQ=
