language: node_js
node_js:
- '10'
sudo: false
git:
  submodules: false
branches:
  only:
  - master
before_script: make init
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
    secure: pb3DRu4AoJJxB+EXisJtXf46KeVpvhcQcH+3sfLD8G/cCGj7L806nIGEdgYdmABKAKUDqhJpcMgjpEJkHHdeyDwAva07tWww+2aZ/CB8jHe867HmDkKsUAZs2n8XQpyRBNj4RtQl4dXxnGiagU+3sMW+fo//qcmLjNmSam8AKjhwfOGHc/CZGEnXhvG5MY36VkB3cJ4a5i69Z3Ey0brzVN+gvMcmB97nX5fR1EO0Bd581wZXhygFg7IeiRie8L43Q7CKsytvdIiPahKoo3r4uaJ/CRkbPLcTqRLUYdXYJ4xgcN3uWXvRfbsMygv36Sk01eaBRR//xTdtRLRFmxt/Zide4qUhiJW5+Qtih1t/qmRkZUI2lSB5oUSMBwNMaspFcmqvTUVYarH24p0nKwMZzn4OkDecrs5m5G0MAQ8Rhjsc+oFKpFxf7p4ugbsoBfeU6EIpm7ESCea8ro/NXXa1bDc96MjlWqu6F/J/2liaSDc4/DL+W8gDvbGc7iPddgQ9OGdJVRgxA0AiaIKLSpfEwJD0dgQjQqFXaNBZYhPaFK1Z6AE3l0h6+uFQG8nXAXBNGDhDsK1MV9lSD5eXZ19GGI93m9PPFRWIg6rlUAIRiO/MsCBIUxVVTVChQgkfdEEmmNMNJkVCNR86j1mxcUpobSm656Xm54whcuEl7tvaArQ=
